service: payment-fiap-pos

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    MONGO_URI: mongodb+srv://fiap-pos:MpQc5Hhd9JTPTKjG@cluster-teste.bwzlfbw.mongodb.net/base_fastfood
    
package:
  individually: true # Define package.individually como true a nível de serviço
  patterns:
    - 'node_modules/**'  # Padrões de pacote a nível de serviço que se aplicam a todas as funções

functions:
  generatepayment:
    handler: src/handler.generatepayment
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240
    events:
      - httpApi:
          path: /generatePayment
          method: post
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto
  searchPaymentByOrderId:
    handler: src/handler.searchPaymentByOrderId
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240 
    events:
      - httpApi:
          path: /searchPaymentByOrderId/{orderId}
          method: get
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto
  payOrderId:
    handler: src/handler.payOrderId
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240 
    events:
      - httpApi:
          path: /payOrderId/{orderId}
          method: put
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto
            
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  
