service: payment-fiap-pos

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
<<<<<<< HEAD
    MONGO_URI: mongodb+srv://fiap-pos:MpQc5Hhd9JTPTKjG@cluster-teste.bwzlfbw.mongodb.net/base_fastfood
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
          Resource:
            - Fn::GetAtt: [criar-pagamento-queue, Arn]
=======
    MONGO_URI: ${env:MONGO_URI}
>>>>>>> 60320ddfff17a28ad605de2c61666d4a0e6fa8f4
    
package:
  individually: true # Define package.individually como true a nível de serviço
  patterns:
    - 'node_modules/**'  # Padrões de pacote a nível de serviço que se aplicam a todas as funções

functions:
  generatepayment:
    handler: src/handler.generatepayment
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240
    events:
      - httpApi:
          path: /generatePayment
          method: post
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto
  searchPaymentByOrderId:
    handler: src/handler.searchPaymentByOrderId
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240 
    events:
      - httpApi:
          path: /searchPaymentByOrderId/{orderId}
          method: get
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto
  payOrderId:
    handler: src/handler.payOrderId
    role: arn:aws:iam::114495730772:role/LabRole
    timeout: 240 
    events:
      - httpApi:
          path: /pay/{orderId}
          method: put
          payload:
            contentHandling: CONVERT_TO_TEXT # Esta opção é importante para garantir que o corpo da solicitação seja enviado como texto  
  processOrder:
    handler: src/handler.processOrder
    events:
      - sqs:
          arn:
            Fn::GetAtt: [criar-pagamento-queue, Arn]
          batchSize: 1

resources:
  Resources:
    criar-pagamento-queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: criar-pagamento-queue

plugins:
  - serverless-offline
  - serverless-plugin-typescript

  
  
