name: Testes de BDD e Cobertura de Testes Unitários

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  TestWithBDD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  

    - name: Instalar dependências
      run: |
        npm install
        sudo apt-get update && sudo apt-get install lcov
        sudo apt-get install jq

    - name: Executar testes BDD e gerar relatório de cobertura
      run: npm run bdd

    - name: Ler informações de cobertura
      run: |
        npm install -g lcov-parse
        lcov-parse coverage/lcov.info > cobertura.json

    - name: Exibir informações de cobertura
      run: cat cobertura.json

    - name: Extrair porcentagem de cobertura
      run: |
        coverage=$(cat cobertura.json | jq '.[].lines.found' | paste -sd+ - | bc)
        cobertos=$(cat cobertura.json | jq '.[].lines.hit' | paste -sd+ - | bc)
        percentual=$(echo "scale=2; $cobertos / $coverage * 100" | bc -l)
        echo "Porcentagem de cobertura: $percentual%"
        pass_percent="1000"
        if (( $(echo "$percentual >= $pass_percent" | bc -l) )); then
          echo "Cobertura de teste atingida: $percentual%"
          exit 0
        else
          echo "Erro: A cobertura de teste é inferior a $pass_percent% ($percentual%)"
          exit 1
        fi

  TestWithUnitTest:
    runs-on: ubuntu-latest
    needs: TestWithBDD
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install
        
      - name: Run unit tests
        run: npm test