name: Testes de BDD e Cobertura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  

    - name: Instalar dependências
      run: npm install

    - name: Executar testes BDD e gerar relatório de cobertura
      run: npm run test

    - name: Mesclar relatórios de cobertura
      run: |
        npm install -g nyc
        nyc cucumber-js -p default --format json:test-results.json && nyc report --reporter=lcov --reporter=text
        mv test-results.json coverage/lcov.info

    - name: Extrair porcentagem de cobertura
      run: |
        coverage=$(cat coverage/lcov.info | lcov --summary | grep 'lines......: ' | awk '{ print $6 }')
        echo "Porcentagem de cobertura: $coverage%"
        pass_percent="80"
        if (( $(echo "$coverage >= $pass_percent" | bc -l) )); then
          echo "Cobertura de teste atingida: $coverage%"
          exit 0
        else
          echo "Erro: A cobertura de teste é inferior a $pass_percent% ($coverage%)"
          exit 1
        fi

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: ${{matrix.os}}-node-${{ matrix.node }}
        parallel: true