name: Testes de BDD e Cobertura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testBdd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  

    - name: Instalar dependências
      run: |
        npm install
        sudo apt-get update && sudo apt-get install lcov
        sudo apt-get install jq

    - name: Executar testes BDD e gerar relatório de cobertura
      run: npm run bdd

    - name: Ler informações de cobertura
      run: |
        npm install -g lcov-parse
        lcov-parse coverage/lcov.info > cobertura.json

    - name: Exibir informações de cobertura
      run: cat cobertura.json

    - name: Extrair porcentagem de cobertura
      run: |
        coverage=$(cat cobertura.json | jq '.[].lines.found' | paste -sd+ - | bc)
        cobertos=$(cat cobertura.json | jq '.[].lines.hit' | paste -sd+ - | bc)
        percentual=$(echo "scale=2; $cobertos / $coverage * 100" | bc -l)
        echo "Porcentagem de cobertura: $percentual%"
        pass_percent="100"
        if (( $(echo "$percentual >= $pass_percent" | bc -l) )); then
          echo "Cobertura de teste atingida: $percentual%"
          exit 0
        else
          echo "Erro: A cobertura de teste é inferior a $pass_percent% ($percentual%)"
          exit 1
        fi

  unit:
    - name: Run tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run unit tests
      run: npm test -- --coverage
    - name: Check coverage
      run: |
        COVERAGE=$(npx istanbul check-coverage --statement 80 --function 80 --lines 80 coverage/coverage-final.json)
        echo "$COVERAGE"
        if [[ "$COVERAGE" != *"All thresholds met"* ]]; then
          echo "Coverage below threshold. Aborting deploy."
          exit 1
        else
          echo "Cobertura de teste unitarios atingidas"
          exit 0
        fi