name: Testes de BDD e Cobertura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  

    - name: Instalar dependências
      run: |
        npm install
        sudo apt-get update && sudo apt-get install lcov

    - name: Executar testes BDD e gerar relatório de cobertura
      run: npm run test

    - name: Ler informações de cobertura
      run: |
        npm install -g lcov-parse
        lcov-parse coverage/lcov.info > cobertura.json

    - name: Exibir informações de cobertura
      run: cat cobertura.json

    - name: Calcular porcentagem de cobertura
      run: |
        const fs = require('fs');

        // Ler o conteúdo do arquivo cobertura.json
        const coberturaJson = fs.readFileSync('cobertura.json', 'utf8');

        // Analisar o conteúdo JSON
        const cobertura = JSON.parse(coberturaJson);

        // Calcular a porcentagem de cobertura
        let totalLinhas = 0;
        let linhasCobertas = 0;

        cobertura.forEach(info => {
          totalLinhas += info.lines.found;
          linhasCobertas += info.lines.hit;
        });

        const porcentagemCobertura = (linhasCobertas / totalLinhas) * 100;
        console.log('Porcentagem de cobertura:', porcentagemCobertura.toFixed(2) + '%')
        
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: ${{matrix.os}}-node-${{ matrix.node }}
        parallel: true